config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :line_items, only: [ :create, :update, :destroy ]
  resources :carts, only: %i[ show destroy ]
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :products do
    resources :subscribers, only: [ :create ]
    resources :reviews, only: [ :new, :create ]
    resources :carts, only: [ :create ]
    get :who_bought, on: :member, defaults: { format: :atom }
  end

  resources :line_items, only: [ :create ]
  resources :users
  resource :unsubscribe, only: [ :show ]

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "products#index"
end

app/models/product.rb
class Product < ApplicationRecord
  include Notifications

  has_many :subscribers, dependent: :destroy
  has_many :reviews, class_name: "Product::Review", dependent: :destroy
  has_many :line_items
  has_many :orders, through: :line_items

  has_one_attached :featured_image
  has_rich_text :description

  validates :name, presence: true
  validates :inventory_count, numericality: { greater_than_or_equal_to: 0 }

  before_destroy :ensure_not_referenced_by_any_line_item

  private

  def ensure_not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, I18n.t("products.errors.line_items_present"))
      throw :abort
    end
  end
end

app/models/product/notifications.rb
module Product::Notifications
  extend ActiveSupport::Concern

  included do
    has_many :subscribers, dependent: :destroy
    after_update_commit :notify_subscribers, if: :back_in_stock?
  end

  def back_in_stock?
    inventory_count_previously_was.zero? && inventory_count > 0
  end

  def notify_subscribers
    subscribers.each do |subscriber|
      ProductMailer.with(product: self, subscriber: subscriber).in_stock.deliver_later
    end
  end
end

app/models/product/review.rb
class Product::Review < ApplicationRecord
  belongs_to :product
  has_rich_text :description

  validates :rating, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
  validates :description, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  allow_unauthenticated_access only: %i[ index show who_bought ]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product, notice: "Product was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to @product
      ActionCable.server.broadcast "products", {
        action: "product_updated",
        product: {
          id: @product.id,
          name: @product.name,
          description: @product.description.body,
          price: @product.price,
          inventory_count: @product.inventory_count
        }
      }
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    was_destroyed = @product.destroy
    unless was_destroyed
      return redirect_to request.referer, alert: @product.errors.full_messages.join(", ")
    end

    redirect_to products_path, notice: "Product was successfully destroyed."
  end

  def who_bought
    @product = Product.find(params[:id])
    @latest_order = @product.orders.order(:created_at).last
    if stale?(@latest_order)
      respond_to do |format|
        format.atom
      end
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
    @reviews = Product::Review.where(product_id: params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.expect(product: [ :name, :description, :featured_image, :inventory_count, :price ])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with model: product, html: { class: "space-y-6" } do |form| %>
  <div>
    <%= form.label :name, class: "block mb-2 text-sm font-medium text-gray-900" %>
    <div class="mt-2">
      <%= form.text_field :name, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5", placeholder: t(".name_placeholder") %>
    </div>
  </div>

  <div>
    <%= form.label :featured_image, class: "block mb-2 text-sm font-medium text-gray-900" %>
    <div class="mt-2">
      <%= form.file_field :featured_image, accept: "image/*", class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5", placeholder: t(".featured_image_placeholder") %>
    </div>
  </div>

  <div>
    <%= form.label :description, class: "block mb-2 text-sm font-medium text-gray-900" %>
    <div class="mt-2">
      <%= form.rich_text_area :description, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5", placeholder: t(".description_placeholder") %>
    </div>
  </div>

  <div>
    <%= form.label :inventory_count, class: "block mb-2 text-sm font-medium text-gray-900" %>
    <div class="mt-2">
      <%= form.number_field :inventory_count, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5", placeholder: t(".inventory_count_placeholder") %>
    </div>
  </div>
  
  <div>
    <%= form.label :price, class: "block mb-2 text-sm font-medium text-gray-900" %>
    <div class="mt-2">
      <%= form.number_field :price, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5", placeholder: t(".price_placeholder") %>
    </div>
  </div>

  <div class="flex justify-between gap-6">
    <%= link_to t(".cancel_button"), products_path, class: "flex w-full items-center justify-center rounded-md border border-gray-300 bg-white px-6 py-2 text-base font-medium text-gray-900 hover:bg-gray-50 focus:ring-2 focus:ring-gray-500 focus:ring-offset-2 focus:outline-hidden" %>
    <%= form.submit t(".submit_button"), class: "flex w-full items-center justify-center rounded-md border border-transparent bg-indigo-600 px-6 py-2 text-base font-medium text-white hover:bg-indigo-700 focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 focus:outline-hidden" %>    
  </div>
<% end %>

app/views/products/_inventory.html.erb
<% if product.inventory_count? %>
  <p><%= product.inventory_count %> in stock</p>
<% else %>
  <p>Out of stock</p>
  <p>Email me when available.</p>

  <%= form_with model: [product, Subscriber.new] do |form| %>
    <%= form.email_field :email, placeholder: "you@example.com", required: true %>
    <%= form.submit "Submit" %>
  <% end %>
<% end %>

app/views/products/edit.html.erb
<h1 class="text-2xl font-bold mb-6">Editing <%= @product.name %></h1>

<%= render "form", product: @product %>

app/views/products/index.html.erb
<section id="products">
  <aside class="flex justify-between items-center mb-6">
    <h1 class="text-2xl font-bold"><%= t ".title" %></h1>
    <%= link_to t(".new_product"), new_product_path, class: "bg-blue-500 text-white px-4 py-2 rounded-md" if authenticated? %>
  </aside>

  <section class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
    <% cache @products do %>
      <% @products.each do |product| %>            
        <%= cache product do %>        
          <div class="max-w-sm rounded bg-white overflow-hidden shadow-lg">
            <%= link_to product do %>
              <%= image_tag product&.featured_image, class: "rounded-t-lg h-50 w-full object-cover" if product.featured_image&.attached? %>
            <% end %>

            <div class="px-6 py-4 h-40 flex flex-col justify-end">
              <%= link_to product.name, product, class: "font-bold text-xl mb-2" %>
              <%= tag.div product.description, class: "truncate text-gray-700" %>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </section>
</section>

app/views/products/new.html.erb
<h1 class="text-2xl font-bold mb-6"><%= t ".title" %></h1>

<%= render "form", product: @product %>

app/views/products/show.html.erb
<main class="product">  
  <div class="flex justify-between gap-2 mb-6 items-center">
    <%= button_to products_path, method: :get, class: "border border-gray-300 text-gray-700 px-4 py-2 rounded-md hover:bg-gray-50 self-start cursor-pointer flex items-center gap-2" do %>
      &larr; <%= t('.back') %>
    <% end %>
    
    <% if authenticated? %>
      <div class="flex gap-2">
        <%= button_to "Edit", edit_product_path(@product), method: :get, class: "bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600 cursor-pointer" %>
        <%= button_to "Delete", @product, method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "bg-red-500 text-white px-4 py-2 rounded-md hover:bg-red-600 cursor-pointer" %>
      </div>
    <% end %>
  </div>

  <section class="rounded-md bg-white overflow-hidden shadow-lg p-6 mb-6">
    <aside class="flex gap-6">
      <div class="h-64 w-64">
        <%= image_tag @product.featured_image, class: "w-full h-full object-cover" if @product.featured_image.attached? %>
      </div>

      <div class="flex flex-col gap-4 flex-1">
        <% cache @product do %>
          <div class="flex items-center gap-4">
            <h1 class="text-2xl font-bold"><%= @product.name %></h1>
            <%= render "inventory", product: @product %>
          </div>
          <p id="product-description" class="text-gray-700"><%= @product.description %></p>
          <p class="text-gray-700">Price: <%= @product.price %></p>
          <%= button_to "Add to cart", line_items_path(product_id: @product.id), class: "bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600 cursor-pointer" %>
        <% end %>
      </div>
    </aside>
  </section>

  <section class="rounded-md bg-white overflow-hidden shadow-lg p-6">
    <div class="flex justify-between items-center mb-6">
      <h2 class="text-2xl font-bold"><%= t('.reviews') %></h2>
      <%= link_to t('.add_review'), new_product_review_path(product_id: @product.id), class: "bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600 cursor-pointer" %>
    </div>

    <% if @reviews.any? %>
      <% @reviews.each do |review| %>      
        <div class="flex flex-col gap-4 mb-6 h-15">
          <div class="flex">
            <% review.rating.times do %>
              <svg class="w-5 h-5 text-yellow-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"/>
              </svg>
            <% end %>
            <% (5 - review.rating).times do %>
              <svg class="w-5 h-5 text-gray-300" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"/>
              </svg>
            <% end %>
          </div>
          <% if review.description? %>
            <div class="text-gray-700">
              <%= review.description %>
            </div>
          <% end %>
        </div>
      <% end %>
    <% else %>
      <p class="text-gray-700"><%= t('.no_reviews') %></p>
    <% end %>
  </section>
</main>