config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :line_items, only: [ :create, :update, :destroy ]
  resources :carts, only: %i[ show destroy ]
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :products do
    resources :subscribers, only: [ :create ]
    resources :reviews, only: [ :new, :create ]
    resources :carts, only: [ :create ]
    get :who_bought, on: :member, defaults: { format: :atom }
  end

  resources :line_items, only: [ :create ]
  resources :users
  resource :unsubscribe, only: [ :show ]

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "products#index"
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :cart, optional: true
  belongs_to :product, optional: true
  belongs_to :order, optional: true

  validates :quantity, presence: true, numericality: { greater_than: 0 }

  def total_price
    product.price * quantity
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart

  before_action :set_cart, only: %i[ create ]
  before_action :set_line_item, only: %i[ update destroy ]

  # POST /line_items or /line_items.json
  def create
    @product = Product.find(params[:product_id])
    @line_item = @cart.add_product(@product)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item.cart, notice: t(".success") }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1 or /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item.cart, notice: t(".success") }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1 or /line_items/1.json
  def destroy
    @line_item.destroy!

    respond_to do |format|
      format.html { redirect_to root_path, status: :see_other, notice: t(".success") }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_line_item
    @line_item = LineItem.find(params.expect(:id))
  end

  # Only allow a list of trusted parameters through.
  def line_item_params
    params.require(:line_item).permit(:product_id)
  end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_with(model: line_item, class: "contents") do |form| %>
  <% if line_item.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(line_item.errors.count, "error") %> <%= t('.prohibited_from_being_saved') %></h2>

      <ul class="list-disc ml-6">
        <% line_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :product_id %>
    <%= form.text_field :product_id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": line_item.errors[:product_id].none?, "border-red-400 focus:outline-red-600": line_item.errors[:product_id].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :cart_id %>
    <%= form.text_field :cart_id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": line_item.errors[:cart_id].none?, "border-red-400 focus:outline-red-600": line_item.errors[:cart_id].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, min: 1, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": line_item.errors[:quantity].none?, "border-red-400 focus:outline-red-600": line_item.errors[:quantity].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<% if line_item == @current_item %>
  <tr class="bg-gray-100" id="current_item">
<% else %>
  <tr>
    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
      <%= line_item.product.name %>
    </td>
    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500 text-right">
      <%= line_item.quantity %>
    </td>
    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500 text-right">
      <%= number_to_currency(line_item.product.price) %>
    </td>
    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500 text-right">
      <%= number_to_currency(line_item.total_price) %>
    </td>
  </tr>
<% end %>

app/views/line_items/_line_item.text.erb
<%= sprintf("%2d &times; %s", line_item.quantity, truncate(line_item.product.name, length: 50)) %>

app/views/line_items/show.html.erb
<% content_for :title, t('.title') %>

<div class="md:w-2/3 w-full">  
  <h1 class="font-bold text-4xl"><%= t('.title') %></h1>

  <%= render @line_item %>

  <%= link_to "Edit this line item", edit_line_item_path(@line_item), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium" %>
  <%= link_to "Back to line items", line_items_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-transparent border border-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <div class="sm:inline-block mt-2 sm:mt-0 sm:ml-2">
    <%= button_to t('.destroy_line_item'), @line_item, method: :delete, class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: t('.confirm_destroy') } %>
  </div>
</div>