config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :line_items, only: [ :create, :update, :destroy ]
  resources :carts, only: %i[ show destroy ]
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :products do
    resources :subscribers, only: [ :create ]
    resources :reviews, only: [ :new, :create ]
    resources :carts, only: [ :create ]
    get :who_bought, on: :member, defaults: { format: :atom }
  end

  resources :line_items, only: [ :create ]
  resources :users
  resource :unsubscribe, only: [ :show ]

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "products#index"
end

app/views/layouts/_sidebar.html.erb
<% if authenticated? %>
  <aside class="h-full w-56 flex flex-col bg-gray-200 py-2">
    <% if session[:cart_id].present? %>
      <%= link_to cart_path(session[:cart_id]), class: "flex items-center py-2 px-3 gap-2 rounded-md hover:bg-gray-300 transition-colors" do %>
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
          <path d="M3 1a1 1 0 000 2h1.22l.305 1.222a.997.997 0 00.01.042l1.358 5.43-.893.892C3.74 11.846 4.632 14 6.414 14H15a1 1 0 000-2H6.414l1-1H14a1 1 0 00.894-.553l3-6A1 1 0 0017 3H6.28l-.31-1.243A1 1 0 005 1H3zM16 16.5a1.5 1.5 0 11-3 0 1.5 1.5 0 013 0zM6.5 18a1.5 1.5 0 100-3 1.5 1.5 0 000 3z" />
        </svg>
        <%= t('.cart') %> (<%= @cart_items_count %>)
      <% end %>      
    <% end %>        

    <%= link_to products_path, class: "flex items-center py-2 px-3 gap-2 rounded-md hover:bg-gray-300 transition-colors" do %>
      <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
        <path d="M7 3a1 1 0 000 2h6a1 1 0 100-2H7zM4 7a1 1 0 011-1h10a1 1 0 110 2H5a1 1 0 01-1-1zM2 11a2 2 0 012-2h12a2 2 0 012 2v4a2 2 0 01-2 2H4a2 2 0 01-2-2v-4z" />
      </svg>
      <%= t('.products') %>
    <% end %>

    <%= link_to users_path, class: "flex items-center py-2 px-3 gap-2 rounded-md hover:bg-gray-300 transition-colors" do %>
      <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
        <path d="M13 6a3 3 0 11-6 0 3 3 0 016 0zM18 8a2 2 0 11-4 0 2 2 0 014 0zM14 15a4 4 0 00-8 0v3h8v-3zM6 8a2 2 0 11-4 0 2 2 0 014 0zM16 18v-3a5.972 5.972 0 00-.75-2.906A3.005 3.005 0 0119 15v3h-3zM4.75 12.094A5.973 5.973 0 004 15v3H1v-3a3 3 0 013.75-2.906z" />
      </svg>
      <%= t('.users') %>
    <% end %>

    <%= link_to orders_path, class: "flex items-center py-2 px-3 gap-2 rounded-md hover:bg-gray-300 transition-colors" do %>
      <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
        <path d="M13 6a3 3 0 11-6 0 3 3 0 016 0zM18 8a2 2 0 11-4 0 2 2 0 014 0zM14 15a4 4 0 00-8 0v3h8v-3zM6 8a2 2 0 11-4 0 2 2 0 014 0zM16 18v-3a5.972 5.972 0 00-.75-2.906A3.005 3.005 0 0119 15v3h-3zM4.75 12.094A5.973 5.973 0 004 15v3H1v-3a3 3 0 013.75-2.906z" />
      </svg>
      <%= t('.orders') %>
    <% end %>
  </aside>    
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full bg-gray-100">
  <head>
    <title><%= content_for(:title) || t('application.title') %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="h-full">
    <nav class="h-12 bg-(--color-primary)">
      <div class="max-w-7xl px-6 mx-auto flex justify-between items-center h-full">
        <%= link_to root_path, class: "text-blue-500 hover:text-blue-700" do %>
          <%= image_tag "/logo.svg", alt: t('application.nav.home'), class: "h-8" %>
        <% end %>
        
        <% if authenticated? %>
          <%= button_to t('application.nav.logout'), session_path, method: :delete, class: "font-medium text-red-600 underline dark:text-red-500 hover:no-underline" %>
        <% else %>
          <%= link_to t('application.nav.login'), new_session_path, class: "font-medium text-blue-600 underline dark:text-blue-500 hover:no-underline" %>
        <% end %>
      </div>
    </nav>
    <main class="flex h-full">
      <%= render "layouts/sidebar" %>

      <section class="h-full p-6 justify-center flex-3 max-w-7xl mx-auto">
        <% if notice.present? %>
          <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
        <% end %>

        <% if alert.present? %>
          <p class="py-2 px-3 bg-red-50 mb-5 text-red-500 font-medium rounded-md inline-block" id="alert"><%= alert %></p>
        <% end %>

        <%= yield %>
      </section>
    </main>
  </body>
</html>